name: GitHub Packages Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sunbox'
          cache: npm
      - run: npm ci
      - name: Get Emscripten
        shell: cmd
        run: |
          subst W: "%GITHUB_WORKSPACE%"
          W:
          call tools\setup_emscripten_win.bat
          set EXIT_CODE=%ERRORLEVEL%
          subst W: /D
          exit /b %EXIT_CODE%
      - name: Build dist
        shell: cmd
        run: |
          subst W: "%GITHUB_WORKSPACE%"
          W:
          call tools\build_wasm_win_dist.bat
          set EXIT_CODE=%ERRORLEVEL%
          subst W: /D
          exit /b %EXIT_CODE%
      - name: Publish GitHub package
        run: npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
