name: WASM Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{matrix.os-type}}

    strategy:
      matrix:
        os-type: [windows-2022]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Get Emscripten
      shell: cmd
      run: |
        subst W: "%GITHUB_WORKSPACE%"
        W:
        call tools\setup_emscripten_win.bat
        set EXIT_CODE=%ERRORLEVEL%
        subst W: /D
        exit /b %EXIT_CODE%
    - name: Build WASM
      shell: cmd
      run: |
        subst W: "%GITHUB_WORKSPACE%"
        W:
        call tools\build_wasm_win.bat Release
        set EXIT_CODE=%ERRORLEVEL%
        subst W: /D
        exit /b %EXIT_CODE%
    - name: Update Package
      run: npm install
    - name: Run Test
      run: npm run test
